# Generated by Django 3.0.2 on 2020-01-30 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('schoolname', models.CharField(blank=True, max_length=256)),
                ('collegename', models.CharField(blank=True, max_length=256)),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('describe', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PROFILE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
