# Generated by Django 3.0.2 on 2020-01-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
