# Generated by Django 3.0.2 on 2020-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profilemodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
