# Generated by Django 3.0.2 on 2020-03-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profilemodel_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='experience',
        ),
    ]
