# Generated by Django 3.0.2 on 2020-02-02 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0004_auto_20200202_0539'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_principal', models.IntegerField(blank=True, null=True)),
                ('rate_director', models.IntegerField(blank=True, null=True)),
                ('rate_tpo', models.IntegerField(blank=True, null=True)),
                ('rate_college', models.IntegerField(blank=True, null=True)),
                ('your_view', models.TextField(blank=True)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('institite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REVIEWS', to='institute.InstituteModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GIVEN_REVIEW', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
