# Generated by Django 3.0.2 on 2020-02-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
