# Generated by Django 3.0.2 on 2020-01-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('doe', models.DateField(null=True)),
                ('area', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('buses', models.BooleanField(default=False)),
                ('canteen', models.BooleanField(default=False)),
                ('describe', models.TextField(blank=True)),
                ('is_university', models.BooleanField(blank=True)),
                ('affiliated_by', models.CharField(blank=True, max_length=256)),
                ('website', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
