# Generated by Django 3.0.2 on 2020-01-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteTPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('experience', models.IntegerField(null=True)),
                ('qualification', models.CharField(blank=True, max_length=256)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('institute_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TPO', to='institute.InstituteModel')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutePrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('experience', models.IntegerField(null=True)),
                ('qualification', models.CharField(blank=True, max_length=256)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('institute_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PRINCIPAL', to='institute.InstituteModel')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='INTITUTE_IMAGES', to='institute.InstituteModel')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('experience', models.IntegerField(null=True)),
                ('qualification', models.CharField(blank=True, max_length=256)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('institute_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DIRECTOR', to='institute.InstituteModel')),
            ],
        ),
    ]
