# Generated by Django 3.0.2 on 2020-01-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_institutedirector_instituteimages_instituteprincipal_institutetpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instituteimages',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='INSTITUTE_IMAGES', to='institute.InstituteModel'),
        ),
    ]
