# Generated by Django 3.0.2 on 2020-02-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20200202_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('pincode', models.IntegerField(null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=8, null=True)),
                ('longititude', models.DecimalField(decimal_places=8, max_digits=8, null=True)),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ADDRESS', to='institute.InstituteModel')),
            ],
        ),
    ]
