# Generated by Django 3.0.2 on 2020-02-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='institute_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ADDRESS', to='institute.InstituteModel'),
        ),
    ]
