# Generated by Django 3.0.2 on 2020-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_auto_20200202_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemodel',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='institutemodel',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='institutemodel',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
