# Generated by Django 3.0.2 on 2020-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_auto_20200203_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemodel',
            name='hostel',
            field=models.BooleanField(default=False),
        ),
    ]
