# Generated by Django 3.0.2 on 2020-02-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_institutemodel_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedirector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/director/'),
        ),
        migrations.AlterField(
            model_name='instituteimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/college/'),
        ),
        migrations.AlterField(
            model_name='institutemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/logo/'),
        ),
        migrations.AlterField(
            model_name='instituteprincipal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/principal/'),
        ),
        migrations.AlterField(
            model_name='institutetpo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/tpo/'),
        ),
    ]
