# Generated by Django 3.0.2 on 2020-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_auto_20200205_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutemodel',
            name='abriviation',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
